import './../css/Faq.css'
import React, { Component } from "react";
import Pergunta from '../../js/Pergunta';

export default class FAQ extends Component {

    click() {
        var elemento = document.getElementById("ites-faq1")
        if (elemento.style.display == "flex")
            elemento.style = "display: none;";
        else
            elemento.style = "display: flex;"
    }

    render() {
        return (
            <div class="escopo-primary">
                <div class="escopo-secundary">
                    <div class="logo-faq">
                        <img src="https://images.emojiterra.com/twitter/512px/1f9d0.png" />
                        <label class="title1">Como podemos ajudar?</label>
                        <label class="title2">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
                            Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                            unknown printer took a galley of type and scrambled it to make a type specimen book.
                            It has survived not only five centuries, but also the leap into electronic
                            typesetting, remaining essentially unchanged.</label>
                    </div>
                    <nav class="lista-faq">
                        <Pergunta id="1" title="O Covid-19 atrapalhou algo na empresa?" sub="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus efficitur mollis tortor id faucibus. Duis sagittis commodo sodales. Mauris a vestibulum diam, ut aliquam risus. Quisque non dolor magna. Nunc lobortis mauris mi, vel venenatis quam tempus eget. Integer luctus nisl vel quam accumsan fermentum. Vivamus pellentesque odio nec porta venenatis.
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus efficitur mollis tortor id faucibus. Duis sagittis commodo sodales. Mauris a vestibulum diam, ut aliquam risus. Quisque non dolor magna. Nunc lobortis mauris mi, vel venenatis quam tempus eget. Integer luctus nisl vel quam accumsan fermentum. Vivamus pellentesque odio nec porta venenatis." />
                        <Pergunta id="2" title="As músicas tocadas podem ser ouvidas a qualquer momento?" sub="Duis pretium viverra pellentesque. Praesent pellentesque commodo lectus faucibus tempus. Suspendisse mattis sagittis porta. Sed vulputate, massa eu facilisis sodales, ligula nisi venenatis est, a scelerisque tellus ex ut augue. Nunc ut tempus arcu. Nulla id ullamcorper velit. Etiam eget dignissim risus. Nullam tincidunt semper eros id porttitor. Cras ut leo interdum, maximus dui quis, feugiat erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras lorem nisi, facilisis a eros porttitor, sagittis pellentesque tellus.Duis pretium viverra pellentesque. Praesent pellentesque commodo lectus faucibus tempus. Suspendisse mattis sagittis porta. Sed vulputate, massa eu facilisis sodales, ligula nisi venenatis est, a scelerisque tellus ex ut augue. Nunc ut tempus arcu. Nulla id ullamcorper velit. Etiam eget dignissim risus. Nullam tincidunt semper eros id porttitor. Cras ut leo interdum, maximus dui quis, feugiat erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras lorem nisi, facilisis a eros porttitor, sagittis pellentesque tellus." />
                        <Pergunta id="3" title="Problemas com conexão?" sub="Nullam pellentesque, quam et aliquet sagittis, urna orci pellentesque massa, quis facilisis sapien urna sed diam. Sed at fermentum quam. Curabitur sit amet iaculis nibh. Praesent iaculis tincidunt magna sit amet dapibus. Fusce tristique mattis mi, at malesuada velit placerat et. Etiam laoreet massa sit amet tellus cursus ullamcorper. Sed sapien augue, iaculis ut consectetur sit amet, luctus id est. Pellentesque in facilisis metus, in porttitor metus.Nullam pellentesque, quam et aliquet sagittis, urna orci pellentesque massa, quis facilisis sapien urna sed diam. Sed at fermentum quam. Curabitur sit amet iaculis nibh. Praesent iaculis tincidunt magna sit amet dapibus. Fusce tristique mattis mi, at malesuada velit placerat et. Etiam laoreet massa sit amet tellus cursus ullamcorper. Sed sapien augue, iaculis ut consectetur sit amet, luctus id est. Pellentesque in facilisis metus, in porttitor metus." />
                        <Pergunta id="4" title="Dúvidas sobre planos" sub="O show gira em torno das aventuras dos membros da família Smith, que consiste nos pais Jerry e Beth, seus filhos Summer e Morty, e o pai de Beth, chamado Rick Sanchez, que mora com eles como hóspede. De acordo com Justin Roiland, a família mora fora da cidade de Seattle, no estado norte-americano de Washington.[2] No entanto, as aventuras de Rick e Morty ocorrem em um número infinito de realidades, com os personagens viajando para outros planetas e dimensões através de portais usando o veículo voador de Rick.

Rick é um cientista louco excêntrico e alcoólatra, que evita muitas convenções costumeiras como escola, casamento, amor e família. Ele frequentemente vai em aventuras com seu neto de 14 anos de idade, Morty, um menino de bom coração, mas que também fica facilmente angustiado, cuja bússola moral ingênua mas fundamentada funciona em contraponto ao ego maquiavélico de Rick. A irmã de Morty, Summer, de 17 anos, é uma adolescente mais convencional, que se preocupa em melhorar seu status social entre seus colegas e às vezes acompanha Rick e Morty em suas aventuras. A mãe das crianças, Beth, é uma pessoa geralmente equilibrada e uma força assertiva no lar, embora consciente de seu papel profissional como médica cirurgiã especializada em cavalos. Ela está insatisfeita com seu casamento com Jerry, uma pessoa insensata e de mente simples, que constantemente desaprova a influência de Rick sobre sua família.

Diferentes versões dos personagens habitam outras dimensões em todo o multiverso e suas características pessoais podem variar de uma realidade para outra. o Rick original do programa se identifica como Rick Sanchez da dimensão da Terra C-137, utilizando esse dado como referência ao seu universo original, mas isso não se aplica necessariamente a todos os outros membros da família Smith. Por exemplo, no episódio Rick Potion #9 da primeira temporada, após transformarem toda a população mundial em monstros, Rick e Morty se mudam para uma dimensão diferente, deixando Summer, Beth e Jerry para trás.

Personagens
Principais

Os membros da família Smith. Da esquerda para à direita: Jerry Smith, Beth Smith, Summer Smith, Morty Smith e Rick Sanchez.
Rick Sanchez C-137 (Voz original: Justin Roiland / Voz no Brasil: Caio César Oliveira (1ª-2ª temporadas) e Ênio Vivona (3ª temporada-atualmente) - Um cientista alcoólatra de 70 anos extremamente inteligente que é capaz de construir máquinas e acessórios tecnológicos que o permitem viajar por diversas dimensões e realidades paralelas. Ele quase nunca pensa nas consequências de suas ações e possui um comportamento excêntrico e um estilo de vida niilista. É pai de Beth, sogro de Jerry e avô de Morty e Summer.
Morty Smith C-137 (Voz original: Justin Roiland / Voz no Brasil: Renan Alonso e Matheus Canella (em Space Jam 2: Um Novo Legado) - Neto facilmente influenciável e com dificuldades escolares de 14 anos de Rick, parece ser a quem este demonstra maior afeto e expectativa dentro da família, o que faz com que ele sempre acabe por acompanhar Rick em suas aventuras, enquanto descobre o que é o próprio mundo real e reflete sobre a existência das coisas.
Jerry Smith (Voz original: Chris Parnell / Voz no Brasil: André Gaiani) - Pai inseguro de Summer e Morty, 35 anos que desaprova fortemente a influência de Rick sobre seu filho. Ele trabalhou em uma agência de publicidade de baixo nível, até que foi demitido por incompetência e agora está desempregado. Tem uma personalidade infantil e impressionável.
Beth Smith (Voz original: Sarah Chalke / Voz no Brasil: Raquel Elaine) - É filha de Rick, esposa de Jerry e mãe de Summer e Morty, aos 34. Como seu pai, ela bebe muito e é bastante inteligente, mas ao contrário dele, é sempre responsável. Ela trabalha em um hospital como cirurgiã de cavalos e muitas vezes se arrepende de não ter sido médica. Ela frequentemente tem discussões com seu marido, vendo uma incompatibilidade em ambos.
Summer Smith (Voz original: Spencer Grammer / Voz no Brasil: Mariana Pozatto) - Tem 17 anos e é a irmã mais velha de Morty, uma adolescente convencional muitas vezes superficial, que é obcecada por melhorar seu status com seus colegas. Ela ocasionalmente expressa inveja por Morty sempre acompanhar Rick em suas aventuras interdimensionais. Na segunda temporada, ela acompanha Rick e Morty com mais freqüência. Foi revelado que Beth tinha engravidado aos 17, a idade que Summer tinha.
Recorrentes
Jessica (Voz original: Kari Wahlgren / Voz no Brasil: Carla Martelli) - Uma menina atraente que frequenta a Harry Herpson High School, mesma escola de Morty e Summer. Morty a ama (embora fique claro na série que boa parte de seu interesse por ela vem de seu corpo), mas ela raramente o reconhece.
Summer, Beth e Jerry C-137 - A família original de Morty e Rick (C-137), que é deixada para trás no final da Primeira Temporada, após Rick acidentalmente transformar todos os humanos do planeta em monstros. Os três são vistos vivendo em cenário pós-apocalíptico no inicio da Terceira Temporada, quando Morty e (a nova) Summer visitam a dimensão C-137.
Presidente Morty (Voz original: Justin Roiland) - O Morty de algum universo desconhecido, é visto inicialmente controlando um Rick robótico para atacar outros Ricks, inclusive o C-137. Após Rick (C-137) matar os membros do Conselho da Cidadela, este Morty é eleito presidente do local, e passa a comandar a Cidadela. Até então suas motivações contra o Rick C-137 são um mistério e alvo de teorias dos fãs da serie.
Pessoa Pássaro (Pessoa Fênix) - (Voz original: Dan Harmon) - Antigo amigo de Rick, é um alienígena parte humanoide, parte ave. Após se apaixonar por Tammy, ambos planejam uma cerimônia de casamento na qual Tammy revela ser uma agente secreta da Federação Galática. Após o acontecido, Pessoa Pássaro fica gravemente ferido e tem vários órgãos substituídos por partes mecânicas, adotando o nome de Pessoa Fênix.
Squanchy - (Voz original: Tom Kenny) - Um dos amigos alienígenas de Rick, Squanchy é um gato antropomórfico amarelo. Muitas vezes utilizado como um alivio cômico por se referir a qualquer coisa através do verbo squanchar. Após a desastrosa cerimõnia de casamento de Pessoa Pássaro, o personagem se manteve desaparecido.
Tammy Gueterman - (Voz original: Cassie Steele) - Uma agente secreta da Federação Galática e interesse romântico de Pessoa Pássaro. É morta por Rick enquanto caçava a Beth do espaço.
Presidente dos Estados Unidos - (Voz original: Keith David) - O presidente dos Estados Unidos da América. Constantemente entra em conflito com Rick e Morty, pois tenta fazer com que ambos atuem ao seu lado contra qualquer ameaça contra a Terra, fazendo Rick se sentir usado.
Beth do Espaço - (Voz original: Sarah Chalke) - É o resultado de uma experiência de Rick, que clona sua filha, Beth, para enviar uma delas ao espaço. Curiosamente, ninguém sabe qual das duas é a Beth real, nem mesmo Rick. No espaço, Beth se tornou líder de uma resistência contra a Federação Galáctica.
Nancy - (Voz original: Aislinn Paul) - Colega de classe e amiga de Summer. É uma das meninas menos populares da série, e por isso é geralmente é evitada por Summer.
Abrodolph Lincoler - (Voz original: Maurice LaMarche) - É um experimento de Rick, que misturou os DNAs de Abraham Lincoln e Adolf Hitler com o intuito de criar um líder político moralmente neutro. Por conta disso, Lincoler sofre um grave transtorno de personalidade e dissonância cognitiva, frequentemente culpando Rick pelo seu sofrimento.
Mr. Goldenfold (Voz original: Brandon Johnson / Voz no Brasil: Ênio Vivona) - É o professor de matemática de Morty. Ele leva seu trabalho muito a sério, e diversas vezes é visto alto proclamando a importância da matemática para sua classe. Ele também tem uma infinidade de atrações sexuais profundamente reprimidas. Sua esposa o deixou, fato que ele enfrenta indo para uma loja de bebidas chamada Jamba Juice.
Gene Vagina (Voz original: Phil Hendrie / Voz no Brasil: Luiz Nunes) - Possui o cargo de diretor da Harry Herpson High School. Ele muitas vezes faz questão de lembrar as pessoas que, apesar de seu sobrenome engraçado, ele é muito responsável.
Brad (Voz original: Echo Kellum/ Voz do Brasil: Renan Villela) - Um estudante em Harry Herpson High School. Ele é um atleta que joga futebol para a escola e namora com Jessica. Ele não aparece na segunda temporada, então presume-se que ele e Jessica Terminaram; pelo fato de Jessica ir ao baile com Morty em Big Trouble in Little Sanchez.
Tricia (Voz original: Cassie Steele) - Amiga e colega de Summer e Jessica. Conhecida como uma das garotas atraentes e populares da escola, namorou Ethan e demonstra interesse sexual por Jerry.
Ethan - (Voz original: Daniel Benson) - O ex-namorado de Summer e hospedeiro do Parque da Anatomia. Após o fim do seu relacionamento, Ethan passa a namorar Tricia, e Summer passa a questionar a sua própria beleza. Após isso, Morty o desfigura horrivelmente para vingar a sua irmã.
Flatulência (Voz original: Jemaine Clement / Voz no Brasil: Tiaggo Guimarães) - Um ser gasoso com a capacidade de ler mentes e alterar a matéria. Sua espécie não tem necessidade de nomes, mas ele passa a se chamar de Flatulência depois que Rick se refere a ele como tal. Por insistência de Morty, ele e Rick ajudam Flatulência a voltar para casa, mas o mesmo é morto por Morty, depois que é revelado que sua espécie vê formas de vida baseadas em carbono como uma doença e planeja limpá-las.
Gazorpazorpfield e Jon (Voz original: Justin Roiland e Tom Kenny, Voz no Brasil: Gustavo Martinez e Renan Alonso, respectivamente) - Personagens de um programa da TV Gazorpian, Gazorpazorpfield, uma paródia de Garfield. Gazorpazorpfield, sendo um Gazorpian macho, é extremamente agressivo por natureza e é visto abusando verbalmente de seu dono, Jon. Rick afirma que Gazorpazorpfield é dublado por Lorenzo Music (a pessoa que dublou o Garfield na vida real até sua morte), que ainda está vivo no universo em que Gazorpazorpfield aparece, ao mesmo tempo alega que Bill Murray o dubla no filme." />
                        <Pergunta id="5" title="Como aderir o plano Premium" sub="Ut malesuada lacinia nulla sed viverra. Nunc non sem imperdiet, faucibus dolor id, condimentum lacus. Nunc suscipit nunc et scelerisque feugiat. Ut aliquet at arcu facilisis pellentesque. Fusce id venenatis dui. Aliquam id malesuada ipsum. Pellentesque accumsan sed sapien at rhoncus. Nullam rhoncus eros id quam dapibus, et iaculis lorem hendrerit. Quisque ultricies in urna a porttitor." />
                        <Pergunta id="6" title="Morty do mal vai retornar?" sub="Sed placerat cursus libero at tempus. Mauris et lobortis lectus. Proin blandit fringilla ultrices. Suspendisse sollicitudin, massa non pretium interdum, ante turpis ultricies odio, id fermentum odio lectus vel erat. Nam fringilla est nec dui vehicula, sit amet interdum nisi posuere. Phasellus condimentum, urna luctus malesuada ultricies, enim mauris ornare enim, vitae tempor quam mi pharetra tortor. Ut pulvinar blandit dui, sit amet tempor risus imperdiet sit amet." />
                            
                    </nav>
                </div>
            </div>
        )
    }

}
